# basic options hash is a comment  
title: New-personal-blog
author: Shengchun Sharon Liu
email: zengyiyang3@gmail.com
description: A lovely wonderful site
twitter_username: jekyllrb
github_username:  shengcode

# Build settings
markdown: kramdown
theme: minima
